### ISSUE TITLE
No more up to date

### ISSUE THREAD

**Issue by mornir** [cfjedimaster/brackets-htmlhint#13]
First of all, a big thanks for this nice plugin 👍 

The linter creator, Yanis Wang, has since then released new versions of this linting tool.
An easy way to keep up to date is to replace the htmlhint.js file in AppData -> Roaming -> Brackets -> extensions -> user -> camden.htmlhint
WITH
https://raw.githubusercontent.com/yaniswang/HTMLHint/master/lib/htmlhint.js

**Comment by cfjedimaster** [comment]
I see you sent a PR - thanks!
