### ISSUE TITLE
wrong cursor positioning when clicking on "<title></title> must not be empty

### ISSUE THREAD

**Issue by JigAma** [cfjedimaster/brackets-htmlhint#15]
Hi, when i click on hint "<title></title> must not be empty."
my cursor should be positionned 
`<title>here</title>`
but it is positionned 
`<title><here/title>
`

**Comment by cfjedimaster** [comment]
I think Git Hub messed up your last line there - but I don't think I can fix this. I'll have to check, but on that rule, I'm not sure the linter returns where the tag center is. In theory I could do some regex to solve that, but as I don't use Brackets anymore and this isn't (imo of course!) a big deal, I may not fix.

**Comment by cfjedimaster** [comment]
I've reproduced it. Seeing if I can fix.

**Comment by cfjedimaster** [comment]
Releasing fixed version now.
